version: '3.8'

services:
  web:
    image: aa:v3
    command: flask run
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://test:test%40123@db/users
      TZ: Asia/Kolkata
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users
      MYSQL_USER: test
      MYSQL_PASSWORD: test@123
      TZ: Asia/Kolkata
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      - TZ=Asia/Kolkata
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge