apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: dXNlcnM=  # base64 encoded value of 'users'
  MYSQL_USER: dGVzdA==  # base64 encoded value of 'test'
  MYSQL_PASSWORD: dGVzdEAxMjM=  # base64 encoded value of 'test@123'
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded value of 'rootpassword'